GET http://localhost:8081/sensing/data
Accept: application/json

###
POST http://localhost:8081/sensing/data
Content-Type: application/json

{
  "sensingList": [
    {
      "value": 1.0
    },
    {
      "value": 2.0
    },
    {
      "value": 3.0
    }
  ]
}
