server:
  port: 8080

spring:
  redis:
    host: 127.0.0.1
    port: 6379

  cloud:
    gateway:
      routes:
        - id: application-route
          uri: http://localhost:8081
          predicates:
            - Path=/sensing/data