version: '3.1'

services:
  api-gateway-server:
    image: nalsm0801/api-gateway-server:0.0.5
    container_name: api-geteway-server-container
    restart: always
    ports:
      - "18080:8080"
    depends_on: [redis]

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "16379:6379"