version: '3.1'

services:
  sensing-application:
    image: nalsm0801/sensing-application:0.0.2
    container_name: sensing-application-container
    restart: always
    ports:
      - "18081:8081"
    depends_on: [ sensing-database ]

  sensing-database:
    image: postgres
    container_name: web-application-db
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"